Repository RomaoFilipe/appDAMA, pull requests merged in 2024-06, with the labels that each got.

#22 App Icon Creation
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/pt/ipt/dama2024/absan/SplashActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/background_bilhar3.png
  app/src/main/res/drawable/background_table.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/logo_black.xml
  app/src/main/res/drawable/logowhite.xml
  app/src/main/res/drawable/mesa.png
  app/src/main/res/drawable/rectangle_button.xml
  app/src/main/res/drawable/rounded_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: help wanted, develop

#23 Dev lagn
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ipt/dama2024/absan/BaseActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/DBHelper.kt
  app/src/main/java/pt/ipt/dama2024/absan/HomeActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/LocaleHelper.kt
  app/src/main/java/pt/ipt/dama2024/absan/LoginActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/MainActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ProfileActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/RegisterActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/User.kt
  app/src/main/java/pt/ipt/dama2024/absan/ui/theme/Color.kt
  app/src/main/java/pt/ipt/dama2024/absan/ui/theme/Theme.kt
  app/src/main/java/pt/ipt/dama2024/absan/ui/theme/Type.kt
  app/src/main/res/drawable/.idea/.gitignore
  app/src/main/res/drawable/.idea/misc.xml
  app/src/main/res/drawable/.idea/modules.xml
  app/src/main/res/drawable/.idea/vcs.xml
  app/src/main/res/drawable/background_gradient.xml
  app/src/main/res/drawable/backperfil.png
  app/src/main/res/drawable/baseline_camera_alt_24.xml
  app/src/main/res/drawable/btn_background_1.xml
  app/src/main/res/drawable/btn_background_2.xml
  app/src/main/res/drawable/btn_background_3.xml
  app/src/main/res/drawable/ic_baseline_person_24.xml
  app/src/main/res/drawable/mesaperfi3.png
  app/src/main/res/drawable/mesaperfile.png
  app/src/main/res/drawable/perfilsicon.png
  app/src/main/res/drawable/settingsicon.png
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/custome_style.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: develop

#25 Home upgrade menu
  app/build.gradle.kts
  app/src/main/java/pt/ipt/dama2024/absan/HomeActivity.kt
  app/src/main/res/anim/button_click.xml
  app/src/main/res/drawable/baseline_assignment_ind_24.xml
  app/src/main/res/drawable/baseline_date_range_24.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: help wanted

#26 Perfil Fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ipt/dama2024/absan/DBHelper.kt
  app/src/main/java/pt/ipt/dama2024/absan/LoginActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ProfileActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/RegisterActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/SchedulelessonactivityActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/User.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/strings.xml
Labels: help wanted

#29 Layout Home
  .idea/other.xml
  app/src/main/java/pt/ipt/dama2024/absan/HomeActivity.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: help wanted

#30 Adding and fixing some comments.
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ipt/dama2024/absan/BaseActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/DBHelper.kt
  app/src/main/java/pt/ipt/dama2024/absan/HomeActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/LocaleHelper.kt
  app/src/main/java/pt/ipt/dama2024/absan/LoginActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ProfileActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/RegisterActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ScheduleLessonFragment.kt
  app/src/main/java/pt/ipt/dama2024/absan/SchedulelessonactivityActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ScoreboardActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/SplashActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/TrainerAdapter.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_schedulelessonactivity.xml
  app/src/main/res/layout/activity_scoreboard.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_schedule_lesson.xml
  app/src/main/res/layout/item_trainer.xml
Labels: develop

#31 Home layout
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ipt/dama2024/absan/BaseActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/DBHelper.kt
  app/src/main/java/pt/ipt/dama2024/absan/HomeActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/LocaleHelper.kt
  app/src/main/java/pt/ipt/dama2024/absan/LoginActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/MainActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ProfileActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/RegisterActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ScheduleLessonFragment.kt
  app/src/main/java/pt/ipt/dama2024/absan/SchedulelessonactivityActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/ScoreboardActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/SoundMonitorActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/SplashActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/TrainerAdapter.kt
  app/src/main/res/drawable/ball_button_background.xml
  app/src/main/res/drawable/ball_button_background_orange.xml
  app/src/main/res/drawable/ball_button_background_red.xml
  app/src/main/res/drawable/baseline_edit_24.xml
  app/src/main/res/drawable/baseline_mic_24.xml
  app/src/main/res/drawable/baseline_person_24_black.xml
  app/src/main/res/drawable/baseline_sports_score_24.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_clock.xml
  app/src/main/res/drawable/ic_remove.xml
  app/src/main/res/drawable/ic_trainer_placeholder.xml
  app/src/main/res/drawable/number_11.xml
  app/src/main/res/drawable/trainer1.jpeg
  app/src/main/res/drawable/trainer2.jpeg
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_schedulelessonactivity.xml
  app/src/main/res/layout/activity_scoreboard.xml
  app/src/main/res/layout/activity_sound_monitor.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_schedule_lesson.xml
  app/src/main/res/layout/item_trainer.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: develop

#32 LastDay FIX
  app/src/main/java/pt/ipt/dama2024/absan/ProfileActivity.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/strings.xml
Labels: develop

#33 Icon app fix.
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: develop

#34 Layout Fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/pt/ipt/dama2024/absan/InfoActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/LoginActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/RegisterActivity.kt
  app/src/main/res/drawable/baseline_info_24.xml
  app/src/main/res/drawable/ic_arrow_white.xml
  app/src/main/res/layout/activity_info.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/strings.xml
Labels: help wanted

#35 Play Store requirements
  app/src/main/java/pt/ipt/dama2024/absan/LoginActivity.kt
  app/src/main/java/pt/ipt/dama2024/absan/SoundMonitorActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sound_monitor.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug
